openapi: 3.0.0
info:
  title: Voter Card Application API SQS Message Types for EROP Clients
  version: '1.2.0'
  description: |-
    Voter Card application API SQS Message Types for EROP Clients
    
    Messages defined in this spec are produced by EROP (VCA and other apps) and consumed by VCA
    
    Whilst this is an openAPI spec, it does not imply being used to define REST APIs, nor is it intended to.
    
    The `paths` elements are being used to document (at a high level) the SQS queues and the request bodies that are expected
    to be published to them. **There is no intent to generate or implement SQS queues or listener classes from this document.**
    
    The `paths` element is only being used in order to maintain the structure of the openApi spec, as `paths` are required 
    elements.
#
# --------------------------------------------------------------------------------
#

paths:
  #
  # --------------------------------------------------------------------------------
  # SQS Queues start here
  # --------------------------------------------------------------------------------
  #
  '/move-certificate-photo':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/S3EventNotificationMessage'
      responses:
        '204':
          description: No response content.
  '/move-erop-uploaded-application-photo':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/S3EventNotificationMessage'
      responses:
        '204':
          description: No response content.
  '/confirm-applicant-register-check-result':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/RegisterCheckResultMessage'
      responses:
        '204':
          description: No response content.
components:
  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:

    S3EventNotificationMessage:
      title: S3EventNotificationMessage
      description: The SQS message that contains information about newly added resource in S3 bucket.
      type: object
      properties:
        Records:
          $ref: '#/components/schemas/S3EventNotifications'
      required:
        - Records
    # Following S3EventNotifications object and it's attributes have been constructed from
    # the sample AWS S3 notification payload and json structure defined on webpage https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html
    S3EventNotifications:
      title: S3EventNotifications
      description: Contains one or more S3 event notification message(s) that Amazon S3 sends to publish s3 related event(s)
      type: array
      items:
        $ref: '#/components/schemas/S3EventNotificationRecord'
    S3EventNotificationRecord:
      title: S3EventNotificationRecord
      description: Notification event message Amazon S3 sends to publish a s3 related event. 
                   Structure is defined on webpage [https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html]
      type: object
      properties:
        eventVersion:
          type: string
          description: Amazon S3 event version
          example: 2.1
        eventSource:
          type: string
          description: Amazon S3 event source
          example: aws:s3
        awsRegion:
          type: string
          description: Amazon S3 aws region
          example: us-west-2
        eventTime:
          type: string
          description: The time in `ISO-8601` format for example [1980-01-01T00:00:00.000Z] when Amazon S3 finished processing the request
          example: 1980-01-01T00:00:00.000Z
        eventName:
          $ref: '#/components/schemas/S3EventType'
        userIdentity:
          $ref: '#/components/schemas/UserIdentity'
        requestParameters:
          $ref: '#/components/schemas/RequestParameters'
        responseElements:
          $ref: '#/components/schemas/ResponseElements'
        s3:
          $ref: '#/components/schemas/S3Detail'
        glacierEventData:
          $ref: '#/components/schemas/GlacierEventData'
      required:
        - eventVersion
        - awsRegion
        - eventTime
        - eventName
        - s3
    S3EventType:
      title: S3EventType
      description: An enumeration of events sent by S3
      type: string
      enum:
        - ObjectCreated:Put
    UserIdentity:
      title: UserIdentity
      type: object
      properties:
        principalId:
          type: string
          description: Amazon customerID of the user who caused the event
          example: AIDAJDPLRKLG7UEXAMPLE
    RequestParameters:
      title: RequestParameters
      type: object
      properties:
        sourceIPAddress:
          type: string
          example: 127.0.0.1
    ResponseElements:
      title: ResponseElements
      description: The responseElements key value is useful if you want to trace a request by following up with AWS Support. Both x-amz-request-id and x-amz-id-2 help Amazon S3 trace an individual request
      type: object
      properties:
        x-amz-request-id:
          type: string
          description: Amazon S3 generated request ID
          example: C3D13FE58DE4C810
        x-amz-id-2:
          type: string
          description: Amazon S3 host that processed the request
          example: FMyUVURIY8/IgAtTv8xRjskZQpcIZ9KG4V5Wp6S7S/JRWeUWerMUE5JgHvANOjpD
    S3Detail:
      title: S3Detail
      type: object
      properties:
        s3SchemaVersion:
          type: string
          description: S3 schema version
          example: "1.0"
        configurationId:
          type: string
          description: ID found in the bucket notification configuration
          example: triggerS3Event-on-photo-upload-config
        bucket:
          $ref: '#/components/schemas/S3DetailBucket'
        object:
          $ref: '#/components/schemas/S3DetailObject'
      required:
        - bucket
        - object
    S3DetailBucket:
      title: S3DetailBucket
      description: S3 bucket details
      type: object
      properties:
        name:
          type: string
          description: Bucket name from where this event came from
          example: vca-example-source-bucket
        ownerIdentity:
          $ref: '#/components/schemas/UserIdentity'
        arn:
          type: string
          description: S3Arn of the resource
          example: arn:aws:s3:::vca-example-source-bucket
      required:
        - name
    S3DetailObject:
      title: S3DetailObject
      description: Object containing details of the resources on S3 bucket
      type: object
      properties:
        key:
          type: string
          description: The s3 key provides information about the bucket and object involved in the event. The object key name value is URL encoded. For example, "red flower.jpg" becomes "red+flower.jpg"
          example: HappyFace.png
        size:
          type: integer
          description: object-size in bytes
          example: 1024
        eTag:
          type: string
          description: object/resource eTag
          example: eTag-d41d8cd98f00b204e9800998ecf8427e
        versionId:
          type: string
          description: object version if bucket is versioning-enabled otherwise null
          example: 096fKKXTRTtl3on89fVO.nfljtsv6qko
        sequencer:
          type: string
          description: A string representation of a hexadecimal value used to determine event sequence only used with PUTs and DELETEs. The sequencer key provides a way to determine the sequence of events. Event notifications aren't guaranteed to arrive in the same order that the events occurred. However, notifications from events that create objects (PUTs) and delete objects contain a sequencer. It can be used to determine the order of events for a given object key
          example: 0055AED6DCD90281E5
      required:
        - key
    GlacierEventData:
      title: GlacierEventData
      description: The glacierEventData key is `only` visible for `[s3:ObjectRestore:Completed]` events.
      type: object
      properties:
        restoreEventData:
          description: The restoreEventData key contains attributes that are related to your restore request.
          type: object
          properties:
            lifecycleRestorationExpiryTime:
              type: string
              description: The lifecycleEventData key is `only` visible for S3 Lifecycle transition events. The time in ISO-8601 format for example 1970-01-01T00:00:00.000Z of Restore Expiry
              example: 1970-01-01T00:00:00.000Z
            lifecycleRestoreStorageClass:
              type: string
              description: Source storage class for restore
    SourceType:
      title: SourceType
      type: string
      enum:
        - voter-card
    RegisterCheckResultMessage:
      title: RegisterCheckResultMessage
      type: object
      description: SQS Message containing an applicant's register check result outcome.
      properties:
        sourceType:
          $ref: '#/components/schemas/SourceType'
        sourceReference:
          type: string
          description: Reference of the application in the corresponding source system that the message relates to. e.g. `VoterCardApplication.applicationId`
          example: 1f0f76a9a66f438b9bb33070
        sourceCorrelationId:
          type: string
          format: uuid
          description: The id to allow the response from rca to be associated with the correct register status e.g. `VoterCardApplicationRegisterStatus.id`
          example: c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd
        registerCheckResult:
          $ref: '#/components/schemas/RegisterCheckResult'
        matches:
          description: Each record in “matches” represents one potential match within the EMS that could represent the Elector in the Register Check Request
          type: array
          items:
            $ref: '#/components/schemas/RegisterCheckMatch'
      required:
        - sourceType
        - sourceReference
        - sourceCorrelationId
        - registerCheckResult
        - matches
    RegisterCheckResult:
      title: RegisterCheckResult
      description: Enum containing the possible values for a register check match outcome.
      type: string
      enum:
        - exact-match
        - partial-match
        - no-match
        - multiple-match
        - too-many-matches
        - pending-determination
        - expired
        - not-started
    RegisterCheckMatch:
      title: RegisterCheckMatch
      description: Object containing the register check match details.
      type: object
      properties:
        personalDetail:
          $ref: '#/components/schemas/RegisterCheckPersonalDetail'
        emsElectorId:
          type: string
          description: The stable unique id of the elector provided by the EMS client
        franchiseCode:
          type: string
          description: Franchise codes indicate the electors voting eligibility within different elections, i.e. national or local elections.
        registeredStartDate:
          type: string
          description: ISO-8601 format. The date the match was registered.
          format: date
          example: 2022-09-01
        registeredEndDate:
          type: string
          description: ISO-8601 format. The date the match was deregistered.
          format: date
          example: 2023-09-01
      required:
        - personalDetail
        - emsElectorId
    RegisterCheckPersonalDetail:
      title: RegisterCheckPersonalDetail
      type: object
      description: Personal details for an applicant
      properties:
        firstName:
          type: string
          description: The applicant's first name
          example: Fred
        middleNames:
          type: string
          description: The applicant's middle name(s)
          example: John
        surname:
          type: string
          description: The applicant's surname
          example: Blogs
        dateOfBirth:
          type: string
          format: date
          description: The applicant's date of birth in ISO-8601. Null if not known
          example: '1981-07-27'
        phone:
          description: The applicant's phone number
          type: string
          example: 01234 567890
        email:
          description: The applicant's email address
          type: string
          example: fred.blogs@some-domain.co.uk
        address:
          $ref: '#/components/schemas/RegisterCheckAddress'
      required:
        - firstName
        - surname
        - address
    RegisterCheckAddress:
      title: RegisterCheckAddress
      description: Address to perform a register check on
      type: object
      x-examples:
        Minimum data:
          street: Street 1
          postcode: PC1 2FB
        Normal Address:
          street: East Lodge
          property: Balruddery
          locality: Invergowrie
          town: Dundee
          area: Angus
          postcode: DD25LF
      properties:
        street:
          type: string
          minLength: 1
          maxLength: 255
          example: Charles Lane
        property:
          type: string
          maxLength: 255
        locality:
          type: string
          maxLength: 255
        town:
          type: string
          maxLength: 255
          example: London
        area:
          type: string
          maxLength: 255
        postcode:
          type: string
          minLength: 1
          maxLength: 10
          example: PE3 6SB
        uprn:
          type: string
          pattern: '^\d{1,12}$'
          maxLength: 12
      required:
        - street
        - postcode
  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses: { }

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    S3EventNotificationMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/S3EventNotificationMessage'
    RegisterCheckResultMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterCheckResultMessage'
