spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/register_checker
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS}

dluhc:
  request.header.name: ${REQUEST_HEADER_CLIENT_CERT_SERIAL}

api:
  ier:
    url: ${API_IER_URL}

sqs:
  ems-cidr-update-queue-name: ${SQS_EMS_CIDR_UPDATE_QUEUE_NAME}