cloud:
  aws:
    region:
      auto: true
      use-default-aws-region-chain: true
    credentials:
      use-default-aws-credentials-chain: true

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/register_checker
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS}

dluhc:
  request.header.name: ${REQUEST_HEADER_CLIENT_CERT_SERIAL}

api:
  ier:
    base.url: ${API_IER_BASE_URL}
    sts.assume.role: ${API_IER_STS_ASSUME_ROLE}

sqs:
  initiate-applicant-register-check-queue-name: ${SQS_INITIATE_APPLICANT_REGISTER_CHECK_QUEUE_NAME}
