cloud:
  aws:
    region:
      auto: true
      use-default-aws-region-chain: true
    credentials:
      use-default-aws-credentials-chain: true

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/register_checker
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS}

dluhc:
  request.header.name: ${REQUEST_HEADER_CLIENT_CERT_SERIAL}

api:
  ero-management:
    url: ${API_ERO_MANAGEMENT_URL}
  ier:
    base.url: ${API_IER_BASE_URL}
    sts.assume.role: ${API_IER_STS_ASSUME_ROLE}

sqs:
  ems-cidr-update-queue-name: ${SQS_EMS_CIDR_UPDATE_QUEUE_NAME}
  initiate-applicant-register-check-queue-name: ${SQS_INITIATE_APPLICANT_REGISTER_CHECK_QUEUE_NAME}
  confirm-applicant-register-check-result-queue-name: ${SQS_CONFIRM_APPLICANT_REGISTER_CHECK_RESULT_QUEUE_NAME}
  remove-applicant-register-check-data-queue-name: ${SQS_REMOVE_APPLICANT_REGISTER_CHECK_DATA_QUEUE_NAME}

caching.time-to-live: PT1H
