spring.datasource:
  url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/register_checker
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  contexts: ${LIQUIBASE_CONTEXTS}
