version: "3.8"
services:
  database:
    image: mysql:8
    container_name: database
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/sql
    ports:
      - 3306:3306
    command: --init-file /sql/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: eipUser
      MYSQL_PASSWORD: eipUserPassword
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=rootPassword
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 45s
    networks:
      - dluhc

  eip-ero-register-checker-api:
    image: eip-ero-register-checker-api:latest
    container_name: eip-ero-register-checker-api
    environment:
      AWS_REGION: eu-west-2
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: rootPassword
      LIQUIBASE_CONTEXTS: ddl
    depends_on:
      - database
    networks:
      - dluhc

networks:
  dluhc:

volumes:
  mysql-data:
  localstack-data:
