name: Build and Test

on: [push]

jobs:
  build-and-test-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # TODO - Add steps to build and test the nextjs application(s)
  build-and-test-api:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Installing JDK needs to come after checking out the repo because the action (setup-java) looks for the gradle wrapper files
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run gradle `check` to lint source code and run tests
        run: ./gradlew clean check --no-daemon
      - name: Save logs on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test logs
          path: |
            eip-ero-register-checker-api/build/reports/tests/test
            eip-ero-register-checker-api/build/test-results/test
