name: Build image and tag for int

on:
  push:
    branches:
      - main
      - feature/EIP1-1634-tagged-deployments

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets['INT_AWS_ACCESS_KEY_ID'] }}
          aws-secret-access-key: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: register-checker-api-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./gradlew bootBuildImage
          docker tag eip-ero-register-checker-api:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      # Explicitly using the git CLI to push tags, to ensure the deployment workflow is triggered.
      - name: Create build tag and update rc/int tag
        id: update-git-tags
        env:
          ENV_TAG: rc/int
        run: |
          # Add build number tag
          git tag -a Build.$GITHUB_RUN_NUMBER
          git push origin Build.$GITHUB_RUN_NUMBER
          
          # Remove env deployment tag
          git tag -d $ENV_TAG
          git push --delete origin $ENV_TAG
          
          # Add env deployment tag
          git tag -a $ENV_TAG
          git push origin $ENV_TAG