name: Deploy a branch to an environment

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - int
          - test
          - pvt
          - sb

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: ${{inputs.deploy_environment}}
    secrets: inherit