name: Deploy a branch to an environment

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to (e.g. test)'
        required: true
        type: string

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/rc/${inputs.deploy_environment}`,
              sha: context.sha,
              force: true,
            });

      - name: Trigger deployment workflow
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-from-tag.yml',
              ref: `refs/tags/rc/${inputs.deploy_environment}`,
            });