name: Deploy to int environment overnight

on:
  schedule:
    - cron: '0 0 * * *' # Every night at midnight

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: int
    secrets: inherit