name: Deploy to int environment overnight

on:
  schedule:
    - cron: '0 1 * * *' # Every night at 1 AM

jobs:
  get-latest-version-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Get latest version tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

  deploy:
    needs: get-latest-version-tag
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: int
      version: ${{ needs.get-latest-version-tag.outputs.version }}
    secrets: inherit
