name: Deploy a branch to an environment

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to (e.g. test)'
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: ${inputs.deploy_environment}
    secrets: inherit