name: Tag main

on:
  push:
    branches:
      - main

jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/Build.${context.runNumber}`,
              sha: context.sha
            })
